apiVersion: batch/v1
kind: Job
metadata:
  name: redis-migrator
spec:
  template:
    spec:
      containers:
      - name: redis-migrator
        image: jruaux/riot-redis:v2.18.4
        command: ["./riot-redis-2.18.4/bin/riot-redis"]
        args: ["-u", $(REDIS_SOURCE), "replicate-ds", "-u", $(REDIS_DEST), "-a", $(REDIS_DEST_PASS)]
        envFrom:
        - secretRef:
            name: redis-creds
      restartPolicy: Never

